### ISSUE TITLE
Request: Conda package

### ISSUE THREAD

**Issue by postelrich** [bokeh/jupyterlab_bokeh#27]
Can a conda package be made for this? Right now the install takes a few minutes to install. Would a conda package be faster? A conda package would allow to list as a requirement in meta/environment.yml.

**Comment by canavandl** [comment]
It's definitely possible to make a conda (and pip) package for this, and generally a good idea to help users make repeatable environments based on environment.yml (or requirement.txt) files.

Unfortunately, I don't believe that a conda package would be faster to install because the "slow" step is when JupyterLab re-webpacks itself to include the extension's JS and CSS.

**Comment by damianavila** [comment]
> Unfortunately, I don't believe that a conda package would be faster to install because the "slow" step is when JupyterLab re-webpacks itself to include the extension's JS and CSS.

Maybe you could do a metapackage containing jupyterlab, bokeh, and jupyterlab_bokeh and perform the re-webpack before creating the final artifact.

**Comment by bryevdv** [comment]
> Unfortunately, I don't believe that a conda package would be faster to install because the "slow" step is when JupyterLab re-webpacks itself to include the extension's JS and CSS.

I agree that a conda package would not do anything to mitigate the slowness of the unavoidable web pack step that will always be necessary on the users side. Therefore there is no benefit to the added complexity and burden of maintaining such a package.
