### ISSUE TITLE
Needed clarity on Bokeh setup in JupyterLab.

### ISSUE THREAD

**Issue by smile-on** [bokeh/jupyterlab_bokeh#53]
In very nice [Bokeh Notebook Setup document](http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/tutorial/00%20-%20Introduction%20and%20Setup.ipynb) simple example shows how easy to get Bokeh output rendered in Jupyter Notebook.

Unfortunately running Jupyter Notebook under Jupyter Lab breakes that simplisity.

``` python
import bokeh
from bokeh.io import output_notebook, show

print(bokeh.__version__)
output_notebook()

0.13.0
Loading BokehJS ...
JavaScript output is disabled in JupyterLab
```

Comments  in JupiterLab issue log re-direct request to Bokeh saying it is security matter and vendor specific plug-in needs to be install. In contrast some users claim it is matter of integration - how you build/install JupyterLab (aka --dev-mode).

The jupyterlab_bokeh plugin README.md just says: **jupyter labextension install jupyterlab_bokeh**
Which is definetly not complete setup, some dependensies are missed.

```shell
$ jupyter labextension install jupyterlab_bokeh

ValueError: Please install nodejs 5+ and npm before continuing....
```
Could someone compile short setup instructions for installing dependencies and running Bokeh under JupyterLab? (not under conda, the real one please :)

**Comment by canavandl** [comment]
@smile-on 

Yes, we are aware that JupyterLab requires installing the ``jupyterlab_bokeh`` extension before bokeh works natively. We (the Bokeh team) wish this wasn't the case, but unfortunately don't have any control over the matter.

My question is: what version of jupyterlab do you have and how do you have it installed?

If you install jupyterlab via conda (``conda install -c conda-forge jupyterlab``) or pip (``pip install jupyterlab``), the installed package should have the necessary dependencies to run ``jupyter labextension install jupyterlab_bokeh`` and have it work.

If you're building jupyterlab from source, you'll almost definitely need to have nodejs and npm in your path.

**Comment by bryevdv** [comment]
Closing for lack of follow up

**Comment by joshmagee** [comment]
Hi, I was wondering if I could follow-up as I am having a similar problem (happy to write a new ticket if that would be more appropriate, or push to another forum).

From jupyter labextenstion list:
    JupyterLab v0.35.4
    jupyterlab_bokeh v0.6.3
From conda list | grep bokeh:
    bokeh v1.0.4

In my notebook I have 
   from bokeh.io import output_notebook
and get the following error: ModuleNotFoundError: No module named 'bokeh.io'; 'bokeh' is not a package. 

I have reinstalled the jupyterlab_bokeh extension and bokeh itself. Any suggestions?

**Comment by bryevdv** [comment]
Speaking from seeing this same experience many, many times now: it is almost 100% the case that you  are unintentionally running jupyterlab from a different environment (i.e. it's not in the activated env, but is in some other env or location further down your path)

**Comment by joshmagee** [comment]
@bryevdv Thanks for the reply. That's interesting since I currently only have one Python environment on this machine (both in conda and jupyter lab). I believe you, but can't find any indication that I'm running a different environment. I know this is old, but could you suggest how to double check in case I'm missing something?

Thanks for your help!

**Comment by bryevdv** [comment]
@joshmagee sure there are a few things:

* does `import bokeh` work in cmd line `python` but not in Jupyter? If so, what is the output of "which jupyter-lab" in a terminal prompt (assuming osx/linux) It's probably different from wherever `python` is located.

* Otherwise, if `import bokeh` works but `from bokeh.io import output_notebook` does not then you must simply have a corrupted bokeh install in site-packages for some reason. Best to blow it away and re-install

**Comment by joshmagee** [comment]
@bryevdv Thanks so much. It turns out I had a corrupted bokeh install and did a full re-install. Seems to work now. Thanks again!
